[package]
name = "arachne-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
num-derive = "0.4.0"
num-traits = "0.2.16"
runtime = { package = "arachne-runtime", path = "../runtime" }

[dev-dependencies]
pretty_assertions = "1.4.0"
