[package]
name = "arachne-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.18.0"
ordered-float = "3.7.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
