[package]
name = "arachne-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.0.1"
nonbox = "0.1.0"
once_cell = { version = "1.19.0", default-features = false }

[dev-dependencies]
pretty_assertions = "1.4.0"
