[package]
name = "arachne-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
runtime = { package = "arachne-runtime", path = "../runtime" }
vm = { package = "arachne-vm", path = "../vm" }

[dev-dependencies]
pretty_assertions = "1.3.0"
