name: bench
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - run: tools/setup.sh
      - run: cargo build --release
      - run: bench/fibonacci/main.sh
