name: bench
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install chezscheme
      - run: |
          old=${{ github.base_ref }}

          if [ -n "$old" ]; then
            git checkout $old
          else
            git checkout HEAD^
          fi

          cargo install --path command
      - run: git checkout ${{ github.sha }}
      - run: tools/bench.sh
