name: bench
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install chezscheme
      - run: |
          old=${{ github.base_ref }}

          if [ -n "$old" ]; then
            git checkout $old
          else
            git checkout HEAD^
          fi

          cargo install --path command
      - run: git checkout ${{ github.sha }}
      - run: tools/bench.sh
