name: bench
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install chezscheme
      - run: |
          old=${{ github.base_ref }}

          git fetch main
          git switch ${old:-HEAD^}
          cargo build --release
          cp target/release/arachne target/release/arachne-old
      - run: git checkout ${{ github.sha }}
      - run: tools/bench.sh
